### ISSUE TITLE
Restful EPP

### ISSUE THREAD

**Issue by vohmar** [CENTRprojects/awesome-dns#5]
### Software name

Restful API for registry-registrar integration

### Software webpage

https://internetee.github.io/repp-apidoc

### Software description

Restful alternative to EPP

### Editing organization

Estonian Internet Foundation

### Category name

API

### New category

- [X] Yes, it's a new category
- [ ] No, it's an existing category

### Motivation

Got a suggestion to propose .ee Rest-EPP implementation for the list. Not sure if this qualifies as its API descritpion not a piece of software on its own, but I'll leave it for you to consider.

### Request checklist

- [x] I have checked for other similar issues and pull requests.
- [x] I have replaced "Software name" by the actual name of the software in the title

- [X] I have filled all mandatory fields

**Comment by thymen** [comment]
Thanks for your suggestion, Timo! My preference would be to limit the scope of this list to tools / software. 

Your API description is great, but if we were to include it, we would actually have to include other DNS related specifications, standards and RFCs as well. I'm afraid the list will then become too long and confusing. 

But since this is a communication effort, I am open to other opinions.

**Comment by vohmar** [comment]
No worries! As I mentioned in the motivation bit, I do agree with your opinion, but as the suggestion came from the community I did my part and created the ticket. The fact that you like the API description made it worth the effort :) You may close the ticket if there is nothing else to discuss here.
